### ISSUE TITLE
AddDivs() breaks color transfer?

### ISSUE THREAD

**Issue by o-smirnov** [gijzelaerr/js9notebook#8]
So my efforts in #6 are producing multiple issues now, @ericmandel:

First, I have this code. Just loading JS9 and making a display:
```
%%html
  <link type="image/x-icon" rel="shortcut icon" href="/static/js9-www/./favicon.ico">
  <link type="text/css" rel="stylesheet" href="/static/js9-www/js9support.css">
  <link type="text/css" rel="stylesheet" href="/static/js9-www/js9.css">
  <link rel="apple-touch-icon" href="/static/js9-www/images/js9-apple-touch-icon.png">
  <script type="text/javascript" src="/static/js9-www/js9prefs.js"></script>
  <script type="text/javascript">
      JS9Prefs.globalOpts.helperPort = 1027;
  </script>
  <script type="text/javascript" src="/static/js9-www/js9support.min.js"></script>
  <script type="text/javascript" src="/static/js9-www/js9.min.js"></script>
  <script type="text/javascript" src="/static/js9-www/js9plugins.js"></script>
<div id='foo'>
<div class='JS9Menubar' id='foo_JS9Menubar'></div><div class='JS9' id='foo_JS9'></div>
<div style='margin-top: 2px;'><div class='JS9Colorbar' id='foo_JS9Colorbar'></div></div>
</div>
<script type="text/javascript">
    JS9.AddDivs("foo_JS9")
    JS9.Preload("/files/vla_L_xx_re.fits",{fits2fits:false},{display:"foo_JS9"})
</script> 
```
The display comes up and appears functional, but the image is completely grey:
![image](https://user-images.githubusercontent.com/6470079/42438349-1a324604-8360-11e8-8ac3-8425dbb9b522.png)

Here's what's funny. If I remove the ``JS9.AddDivs("foo_JS9")`` statement, everything works fine.

**Comment by ericmandel** [comment]
The foo_JS9 div is part of the web page from the start (i.e. not added programmatically), so the (equivalent of) JS9.AddDivs() has already been called on it. I'm not sure what happens if you call it again explicitly, but I can imagine that something bad happens.

**Comment by o-smirnov** [comment]
Ah ok, got it.

**Comment by o-smirnov** [comment]
Hmmm, on second thought, that can't be the whole answer. In the example above, the div is actually **not** part of the web page from the start. That HTML code is just some text sitting in a text box in a Jupyter cell -- it doesn't get added to the DOM until the notebook (or cell) is executed, at which point the HTML is added programmatically. 

So why do I **not** need AddDivs in this case? Is it perhaps the divs are part of the same chunk of HTML code that invokes the JS? So by the time the JS is loaded, the divs already exist?

**Comment by ericmandel** [comment]
Sorry, I didn't quite mean from the start, I mean at the time that JS9.init() is called. In the above example, you add a bunch of divs to the DOM and load a bunch of scripts, including js9.js. When its loaded and ready, the js9.js script calls JS9.init() which essentially calls JS9.AddDivs() on the existing divs, which includes the divs within foo". Once this is done, if you add more divs, you have to call JS9.AddDivs() manually.

**Comment by o-smirnov** [comment]
OK that makes sense then.
