### ISSUE TITLE
Trying to decouple JS9 load from JS9 window creation under Jupyter

### ISSUE THREAD

**Issue by o-smirnov** [gijzelaerr/js9notebook#9]
Following on from #6, I would like to load the JS9 files just once (say, when the first cell of the notebook is executed), and then create one or more displays in other cells. I'm getting some unexpected behaviour from this. Here's the simplest example I can break it down to (NB: I'm actually trying to do this programmatically of course, but for the purposes of illustrating the problem, I've reproduced it using raw HTML in the notebook).

So I have a very simple notebook, just %%html and %%javascript cells. Cell 1 loads JS9:
```
%%html
  <link type="image/x-icon" rel="shortcut icon" href="/static/js9-www/./favicon.ico">
  <link type="text/css" rel="stylesheet" href="/static/js9-www/js9support.css">
  <link type="text/css" rel="stylesheet" href="/static/js9-www/js9.css">
  <link rel="apple-touch-icon" href="/static/js9-www/images/js9-apple-touch-icon.png">
  <script type="text/javascript" src="/static/js9-www/js9prefs.js"></script>
  <script type="text/javascript">
      JS9Prefs.globalOpts.helperPort = 1027;
  </script>
  <script type="text/javascript" src="/static/js9-www/js9support.min.js"></script>
  <script type="text/javascript" src="/static/js9-www/js9.min.js"></script>
  <script type="text/javascript" src="/static/js9-www/js9plugins.js"></script>
```

Cell 2 just checks for the JS9 object. The object is printed the the console, so I know it's been loaded:
```
%%javascript 
console.log(JS9)
```

Cells 3 and 4 try to load two different displays:
```
<div id='foo'>
<div class='JS9Menubar' id='foo_JS9Menubar'></div>
<div class='JS9' id='foo_JS9'></div>
<div style='margin-top: 2px;'><div class='JS9Colorbar' id='foo_JS9Colorbar'></div></div>
</div>
<script type="text/javascript">
    JS9.Preload("/files/vla_L_xx_re.fits",{fits2fits:false},{display:"foo_JS9"})
</script>     
```
```
%%html
<div id='foo1'>
<div class='JS9Menubar' id='foo1_JS9Menubar'></div>
<div class='JS9' id='foo1_JS9'></div>
<div style='margin-top: 2px;'><div class='JS9Colorbar' id='foo1_JS9Colorbar'></div></div>
</div>
<script type="text/javascript">
    JS9.Preload("/files/vla_L_yy_re.fits",{fits2fits:false},{display:"foo1_JS9"})
</script> 
```

I observe the following:

* If I run all four in sequence, cells 3 and 4 don't produce any displays.

* If I then go back and re-run cell 1 (with Ctrl+Enter), thus reloading the JS9 scripts, two JS9 windows suddenly appear in cells 3 and 4. But they're not functional ("no FITS module available"... but I've began to associate this error with loading JS9 twice in a webpage -- it seems after a second load, this error always starts popping up.)

* Fresh restart (Kernel|Restart and clear output, then reload the browser page -- this is necessary to clear JS9 out of memory)

* If I append the code from cell 3 to the bottom of cell 1 (so now I'm loading JS9 and opening a display in a single cell, in one go), I get a fully functional display

* If I then execute cell 4 -- hoping for a second display -- I get no output.

* If I re-execute cell 1, I now have a broken display in cell 1, and a new, broken, display appears in cell 4

So there's obviously some unholy interaction going on, but I'm stumped at this point. @ericmandel, could you please try to reproduce this scenario in a notebook on your end?

**Comment by ericmandel** [comment]
I will try to reproduce this, but it might take a while to get through my other Monday problems ...
Can please tell me where to put the link to JS9 so that I can use your technique?

Also, do you know what happens when you add the html code to cell 3 and 4? Does Jupyter inject the html programmatically into the existing DOM? If so, that probably means you need to call JS9.AddDivs() before JS9.Preload() because you have added divs but have not told JS9 about them. I also would change JS9.Preload to JS9.Load, since JS9 is already initialized in called #1.

**Comment by o-smirnov** [comment]
Awesome, using AddDivs() and Load() solves this problem -- don't bother reproducing just yet!

> Also, do you know what happens when you add the html code to cell 3 and 4? Does Jupyter inject the html programmatically into the existing DOM?

Exactly.

As for symlinks: ``X/lib/python2.7/site-packages/notebook/static/js9-www`` needs to point to your JS9 install, where X corresponds to where your Python is installed. X=/usr if it's sytemwide, but if you're using a virtualenv, then X is the path of the virtualenv.

**Comment by o-smirnov** [comment]
OK, so I think this is starting to work. I must just take care to never never load JS9 twice, but I can figure out how to do that.

**Comment by o-smirnov** [comment]
Excellent, it's quite robust now, and I can have multiple JS9's in multiple cells. The init trick is here:

https://github.com/ratt-ru/radiopadre-devel/blob/devel-lexy/radiopadre/js9/__init__.py#L53

**Comment by ericmandel** [comment]
This looks terrific, so far as I can understand with my tyro-level understanding of Python. Especially since I don't see a good way to avoid the effects of double-loading JS9 from my side.

Amazing progress for a week's work. So far as I understand, I still owe you the following:

1. a fix for the bug when you load the full image and get increasingly smaller results
2. an extension to binning that returns the mean instead of the sum of binned pixel values

Did I miss anything (aside from the prototype large file panner)?

**Comment by o-smirnov** [comment]
> Amazing progress for a week's work. So far as I understand, I still owe you the following:

Yes please. :) Those two and the panner (which I can almost cobble together myself, if I can get past those error messages in the event handlers, see https://github.com/ratt-ru/radiopadre-devel/issues/4).

I'm going to start closing issues as they become resolved, so it's easier to keep track of what actually still needs looking at.

There's now a layout problem, but that's for a separate issue...
